"use client";

import React, { useState } from 'react';
import { HiOutlineSearch, HiChevronDown } from 'react-icons/hi';

interface FAQItem { question: string; answer: string; }
interface FAQCategory { title: string; items: FAQItem[]; }

const faqData: FAQCategory[] = [
  {
    title: "General FAQ",
    items: [
      { question: "What is Humanize AI?", answer: "Humanize AI is a free online tool that converts AI-generated text into natural, human-sounding content. It rewrites robotic or mechanical language produced by AI tools so it reads like it was written by a real person — while keeping the original meaning intact." },
      { question: "Is Humanize AI completely free to use?", answer: "Yes. Humanize AI is 100% free with no hidden charges, subscription fees, or usage limits. You can use it as many times as you need without paying anything." },
      { question: "Do I need to create an account to use the tool?", answer: "No. There is no registration or sign-up required. Simply visit the website, paste your text, and start humanizing immediately." },
      { question: "What AI tools does Humanize AI support?", answer: "Humanize AI can rewrite content generated by ChatGPT, Google Gemini, Microsoft Copilot, QuillBot, Jasper, Grammarly, Copy.ai, and most other AI writing platforms." },
      { question: "Is this really free with no limits?", answer: "Yes. Humanize AI is completely free with no word caps and no usage restrictions. You never need to upgrade to access the full tool." },
      { question: "Can a free AI humanizer match the quality of paid tools?", answer: "For most everyday use cases blogging, marketing copy, emails, and social media yes. The quality is high enough that most users have no need for a paid alternative." }
    ]
  },
  {
    title: "SEO & Performance",
    items: [
      { question: "Will humanized content rank better on Google?", answer: "Yes. Search engines like Google reward content that is original, readable, and genuinely useful. Humanized content is more natural and engaging, which improves key SEO metrics like time-on-page, bounce rate, and overall content quality scores." },
      { question: "Does Humanize AI make content SEO-friendly?", answer: "Yes. The tool retains your important keywords naturally within the rewritten text, which helps your content maintain its SEO relevance while also improving readability for human visitors." },
      { question: "Is the output plagiarism-free?", answer: "Yes. Every rewrite is freshly generated and unique. The tool does not copy from any external source, so the output is original and free from plagiarism." },
      { question: "Can humanized content pass AI detection tools?", answer: "Humanize AI rewrites content to closely resemble natural human writing. The output is designed to pass most AI detection systems by eliminating patterns typical of AI-generated text. However, results may vary depending on the detection tool used and the complexity of the original content." },
      { question: "Is humanized content safe to use on AdSense-monetized websites?", answer: "Yes. Google AdSense requires original, high-quality content that provides real value to readers. Content processed through Humanize AI is rewritten to be natural, readable, and genuinely informative — which aligns with AdSense content quality guidelines." },
      { question: "Can I use this tool to create content for a blog I plan to monetize?", answer: "Yes. Humanized content is suitable for monetized blogs, provided you review the output and ensure it meets your website's quality standards before publishing. Always read and lightly edit the final output before going live." },
      { question: "Will Google penalize my site if I use AI-generated content?", answer: "Google's policies focus on content quality and user value, not the method of creation. Content that is original, helpful, and well-written regardless of whether AI was involved in drafting it can rank and be monetized. Humanize AI helps ensure your content meets those quality standards." }
    ]
  },
  {
    title: "Features & Usage",
    items: [
      { question: "Can I use the tool multiple times on the same content for better results?", answer: "Yes. If you want a more refined output, you can run the tool again on the same text. Each pass may produce slightly different results, giving you options to choose the best version." },
      { question: "Does the tool change the meaning of my content?", answer: "No. Humanize AI is designed to preserve your original message and context. It improves the tone, flow, and readability of your text without altering what you are trying to say." },
      { question: "What languages does Humanize AI support?", answer: "The tool supports multiple languages including English, Arabic, Chinese, Russian, and Japanese. Support for additional languages is expanding." },
      { question: "Does it work on mobile devices?", answer: "Yes. Humanize AI works on all devices including smartphones, tablets, laptops, and desktops." },
      { question: "Which browsers are compatible with the tool?", answer: "The tool is fully compatible with all major browsers including Google Chrome, Mozilla Firefox, Apple Safari, and Microsoft Edge." },
      { question: "What should I do if the output does not seem natural enough?", answer: "Try running the humanization process a second time on the same content. You can also manually edit specific phrases after the tool processes the text. For best results, review and lightly personalize the output before publishing." },
      { question: "Why does the tool ask me to complete a captcha?", answer: "The captcha is a simple security step to confirm you are a real user and to prevent automated misuse of the tool. It only takes a moment to complete." },
      { question: "Is there a word or character limit for input text?", answer: "The tool is designed to handle standard content lengths efficiently. For very long documents, consider splitting the content into sections and processing each part separately for the best results." }
    ]
  },
  {
    title: "Safety & Privacy",
    items: [
      { question: "Is my content safe when I use Humanize AI?", answer: "Yes. Your privacy is a priority. The content you submit is not stored, shared, or used for any other purpose. Everything you input remains confidential." },
      { question: "Does the tool store my text after processing?", answer: "No. The tool does not retain your content after the session ends. Your data is processed and discarded immediately after use." }
    ]
  }
];

const FAQ: React.FC = () => {
  const [activeItem, setActiveItem] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState("");

  const toggleItem = (id: string) => setActiveItem(activeItem === id ? null : id);

  const filteredData = faqData.map(category => ({
    ...category,
    items: category.items.filter(item =>
      item.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.answer.toLowerCase().includes(searchTerm.toLowerCase())
    )
  })).filter(category => category.items.length > 0);

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16 sm:py-32">
      <div className="text-center mb-10 sm:mb-16 animate-fade-in">
        <h1 className="text-3xl sm:text-5xl md:text-6xl font-extrabold gradient-heading tracking-tighter mb-4 sm:mb-6" style={{ fontFamily: 'var(--font-heading)' }}>
          Got Questions?
        </h1>
        <p className="text-base sm:text-xl leading-relaxed mb-6 sm:mb-10 max-w-xl mx-auto" style={{ color: 'var(--muted)' }}>
          Everything you need to know about our AI-powered humanization and detection engines.
        </p>
        <div className="relative max-w-lg mx-auto">
          <input
            type="text"
            placeholder="Search for a topic or keyword..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full py-3 sm:py-4 pl-5 sm:pl-6 pr-12 sm:pr-14 rounded-2xl bg-white text-sm sm:text-base font-medium outline-none transition-all duration-300"
            style={{ border: '1px solid var(--border)', color: 'var(--text)' }}
            onFocus={e => { e.target.style.borderColor = 'var(--primary)'; e.target.style.boxShadow = '0 0 0 4px var(--primary-soft)'; }}
            onBlur={e => { e.target.style.borderColor = 'var(--border)'; e.target.style.boxShadow = 'none'; }}
          />
          <span className="absolute right-4 sm:right-5 top-1/2 -translate-y-1/2 text-xl" style={{ color: 'var(--muted)' }}><HiOutlineSearch /></span>
        </div>
      </div>

      <div className="flex flex-col gap-8 sm:gap-12">
        {filteredData.length > 0 ? (
          filteredData.map((category, catIdx) => (
            <div key={catIdx} className="flex flex-col gap-3 sm:gap-4">
              <h2 className="text-sm sm:text-lg font-extrabold uppercase tracking-widest text-theme" style={{ fontFamily: 'var(--font-heading)' }}>
                {category.title}
              </h2>
              <div className="flex flex-col gap-2 sm:gap-3">
                {category.items.map((item, itemIdx) => {
                  const id = `${catIdx}-${itemIdx}`;
                  const isOpen = activeItem === id;
                  return (
                    <div key={id} className="rounded-2xl transition-all duration-300 overflow-hidden bg-white"
                      style={{ border: isOpen ? '1px solid var(--primary)' : '1px solid var(--border)', boxShadow: isOpen ? '0 10px 25px rgba(0,0,0,0.05)' : 'none' }}
                    >
                      <button
                        className="w-full flex items-center justify-between p-4 sm:p-6 text-left bg-transparent border-none cursor-pointer text-sm sm:text-base font-bold leading-snug"
                        style={{ color: 'var(--text)' }}
                        onClick={() => toggleItem(id)}
                        aria-expanded={isOpen}
                      >
                        {item.question}
                        <span className="text-theme text-lg sm:text-xl flex-shrink-0 ml-3 sm:ml-4 transition-transform duration-300" style={{ transform: isOpen ? 'rotate(180deg)' : 'none' }}>
                          <HiChevronDown />
                        </span>
                      </button>
                      <div className="transition-all duration-300 overflow-hidden" style={{ maxHeight: isOpen ? '400px' : '0', opacity: isOpen ? 1 : 0 }}>
                        <p className="px-4 sm:px-6 pb-4 sm:pb-6 text-sm sm:text-base leading-relaxed" style={{ color: 'var(--muted)' }}>{item.answer}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ))
        ) : (
          <div className="text-center py-12 sm:py-16" style={{ color: 'var(--muted)' }}>
            <p>No results found for &quot;{searchTerm}&quot;. Try focusing on keywords like &quot;bypass&quot; or &quot;privacy&quot;.</p>
          </div>
        )}
      </div>

      <div className="text-center mt-12 sm:mt-20 py-10 sm:py-16" style={{ borderTop: '1px solid var(--border)' }}>
        <h3 className="text-xl sm:text-2xl font-extrabold mb-3" style={{ color: 'var(--text)', fontFamily: 'var(--font-heading)' }}>Still curious?</h3>
        <p className="mb-6 sm:mb-8" style={{ color: 'var(--muted)' }}>Our support team is ready to help you with any unique technical needs.</p>
        <a
          href="mailto:support@Humanize AI.ai"
          className="inline-block px-6 sm:px-8 py-3 sm:py-4 bg-theme text-white rounded-2xl font-bold text-sm sm:text-base no-underline shadow-theme hover:-translate-y-0.5 transition-all duration-300"
        >
          Contact Our Team
        </a>
      </div>
    </div>
  );
};

export default FAQ;
